name: Deploy staging website
inputs:
  header_name:
    required: true
  header_value:
    required: true
  webhook_endpoint:
    required: true

runs:
  using: "composite"
  steps:
    - name: Call webhook
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      shell: bash
      run: |
        curl -X POST -H "${{ inputs.header_name }}: ${{ inputs.header_value }}" ${{ inputs.webhook_endpoint }} -H "Content-Type: application/json" -d null
