name: Docker build
inputs:
  image_name:
    description: docker image name
    required: true
    type: string
  dockerhub_username:
    description: docker hub username
    type: string
  dockerhub_token:
    description: docker hub token
    type: string
  dockerfile:
    description: dockerfile name
    type: string
    default: Dockerfile
  context:
    description: context path
    type: string
    default: .

runs:
  using: "composite"
  steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ inputs.image_name }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=sha

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Set output
      id: vars
      shell: bash
      run: |
        echo "GIT_COMMIT=$(git describe --tags)" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: ${{ inputs.dockerfile }}
        context: ${{ inputs.context }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: GIT_COMMIT=${{ steps.vars.outputs.GIT_COMMIT }}
