name: docker-build

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerhub_username:
        required: true
        type: string
      dockerfile:
        type: string
        default: Dockerfile
      context:
        type: string
        default: .
    secrets:
      dockerhub_token:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: geokrety/geokrety-gha-workflows/.github/actions/docker-build@main
        with:
          image_name: ${{ inputs.image_name }}
          dockerhub_username: ${{ inputs.dockerhub_username }}
          dockerhub_token: ${{ secrets.dockerhub_token }}
          dockerfile: ${{ inputs.dockerfile }}
          context: ${{ inputs.context }}
