name: docker-build

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerhub_username:
        required: true
        type: string
      dockerfile:
        type: string
        default: Dockerfile
      context:
        type: string
        default: .
      push:
        type: boolean
        default: true
    secrets:
      dockerhub_token:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        shell: bash
        run: |
          # DEBUG FROM WORKFLOW
          # github.event_name: ${{ github.event_name }} push
          # inputs.push: ${{ inputs.push }} true
          # cond1: ${{ github.event_name != 'pull_request' }} true
          # cond2: ${{ inputs.push }} false
          # cond2: ${{ inputs.push == 'true' }} false
          # result: ${{ github.event_name != 'pull_request' && inputs.push }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: geokrety/geokrety-gha-workflows/.github/actions/docker-build@main
        with:
          image_name: ${{ inputs.image_name }}
          dockerhub_username: ${{ inputs.dockerhub_username }}
          dockerhub_token: ${{ secrets.dockerhub_token }}
          dockerfile: ${{ inputs.dockerfile }}
          context: ${{ inputs.context }}
          push: ${{ github.event_name != 'pull_request' && inputs.push }}
