name: pre-commit

on:
  pull_request:
  push:
    branches:
      - '!main'
  workflow_call:

jobs:
  pre-commit:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: geokrety/geokrety-gha-workflows/.github/actions/pre-commit
