name: pre-commit

on:
  pull_request:
  push:
    branches:
      - '!main'
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: geokrety/geokrety-gha-workflows/.github/actions/pre-commit@main
