name: pre-commit

on:
  pull_request:
  push:
    branches:
      - '!main'
  workflow_call:

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/pre-commit.yml
