name: Automatic release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pre-commit
      - uses: ./.github/actions/semantic-release
        with:
          token: ${{ secrets.GH_TOKEN }}
