name: Automatic release
# Use this one for default pre-commit pre-installed tools

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  pre-commit:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/pre-commit.yml@main

  build-release:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/semantic-release.yml@main
    needs: pre-commit
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
