name: Automatic release with Dockerfile
# Use this one for default pre-commit pre-installed tools and a standard dockerfile

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      image_name:
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  pre-commit:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/pre-commit.yml@main

  docker:
    needs: pre-commit
    uses: geokrety/geokrety-gha-workflows/.github/workflows/docker-build.yml@main
    with:
      image_name: ${{ inputs.image_name }}
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      dockerfile: Dockerfile
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-release:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/semantic-release.yml@main
    needs: docker
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
