name: Automatic release

on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/pre-commit.yml
      - uses: ./.github/actions/semantic-release.yml
        with:
          token: ${{ secrets.GH_TOKEN }}
