name: Automatic release with Dockerfile
# Use this one for default pre-commit pre-installed tools and a standard dockerfile

on:
  workflow_call:
    inputs:
      image_name:
        type: string
      dockerhub_username:
        required: true
        type: string
      dockerfile:
        type: string
        default: Dockerfile
      context:
        type: string
        default: .
    secrets:
      GH_TOKEN:
        required: true
      dockerhub_token:
        required: true

jobs:
  pre-commit:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/pre-commit.yml@main

  docker:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/docker-build.yml@main
    needs: pre-commit
    with:
      image_name: ${{ inputs.image_name }}
      dockerhub_username: ${{ inputs.dockerhub_username }}
      dockerfile: ${{ inputs.dockerfile }}
      context: ${{ inputs.context }}
    secrets:
      dockerhub_token: ${{ secrets.dockerhub_token }}

  build-release:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/semantic-release.yml@main
    needs: docker
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
