name: Automatic release

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  # pre-commit:
  #   if: "!contains(github.event.head_commit.message, 'skip ci')"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: geokrety/geokrety-gha-workflows/.github/actions/pre-commit@main

  semantic-release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    # needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: geokrety/geokrety-gha-workflows/.github/actions/semantic-release@main
        with:
          token: ${{ secrets.GH_TOKEN }}
