name: Automatic release
# Use this one for custom pre-commit config (needing custom tools)

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  build-release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: geokrety/geokrety-gha-workflows/.github/actions/semantic-release@main
        with:
          token: ${{ secrets.GH_TOKEN }}
