name: Update version-set

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  versionset:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/version-set
