name: Update version-set

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  versionset:
    if: "startsWith(github.ref, 'refs/tags/v')"
    runs-on: ubuntu-latest
    steps:
      - uses: geokrety/geokrety-gha-workflows/.github/actions/version-set@main
        with:
          token: ${{ secrets.GH_TOKEN }}
