name: Update version-set

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  versionset:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: geokrety/geokrety-gha-workflows/.github/actions/version-set
        with:
          token: ${{ secrets.GH_TOKEN }}
